// <auto-generated />
using BankDataWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251009031430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.Property<uint>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Pin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNo");

                    b.HasIndex("UserName");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNo = 1u,
                            AccountType = "savings",
                            Balance = 0m,
                            Pin = 3423u,
                            UserName = "sophia3423"
                        },
                        new
                        {
                            AccountNo = 2u,
                            AccountType = "cheque",
                            Balance = 0m,
                            Pin = 4353u,
                            UserName = "john4534"
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Transaction", b =>
                {
                    b.Property<uint>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegal")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("TargetAccountNo")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1u,
                            AccountNo = 1u,
                            Amount = 134m,
                            IsLegal = true
                        },
                        new
                        {
                            TransactionId = 2u,
                            AccountNo = 2u,
                            Amount = 293m,
                            IsLegal = true
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Password")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "sophia3423",
                            Email = "sophia3423@gmail.com",
                            FirstName = "Sophia",
                            LastName = "Matassa",
                            Password = "9348230249",
                            PhoneNo = 423434332
                        },
                        new
                        {
                            UserName = "john4534",
                            Email = "john4534@gmail.com",
                            FirstName = "John",
                            LastName = "Small",
                            Password = "342345435",
                            PhoneNo = 458392394
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.HasOne("BankDataWebService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
