// <auto-generated />
using BankDataWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    [Migration("20251007010938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.Property<uint>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<uint>("Pin")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountNo");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNo = 1u,
                            AccountType = "savings",
                            Balance = 0m,
                            Pin = 3423u,
                            UserId = 1u
                        },
                        new
                        {
                            AccountNo = 2u,
                            AccountType = "cheque",
                            Balance = 0m,
                            Pin = 4353u,
                            UserId = 2u
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Transaction", b =>
                {
                    b.Property<uint>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("ReceivingAccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("SendingAccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeStamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("ReceivingAccountNo");

                    b.HasIndex("SendingAccountNo");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1u,
                            Amount = 134m,
                            SendingAccountNo = 1u,
                            TimeStamp = "2024-12-02 16:43:03"
                        },
                        new
                        {
                            TransactionId = 2u,
                            Amount = 293m,
                            SendingAccountNo = 2u,
                            TimeStamp = "2025-01-03 18:52:17"
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.User", b =>
                {
                    b.Property<uint>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Password")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1u,
                            Email = "sophia3423@gmail.com",
                            FirstName = "Sophia",
                            LastName = "Matassa",
                            Password = "9348230249",
                            PhoneNo = 423434332
                        },
                        new
                        {
                            UserId = 2u,
                            Email = "john4534@gmail.com",
                            FirstName = "John",
                            LastName = "Small",
                            Password = "342345435",
                            PhoneNo = 458392394
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.HasOne("BankDataWebService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankDataWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankDataWebService.Models.Account", "ReceivingAccount")
                        .WithMany()
                        .HasForeignKey("ReceivingAccountNo");

                    b.HasOne("BankDataWebService.Models.Account", "SendingAccount")
                        .WithMany()
                        .HasForeignKey("SendingAccountNo");

                    b.Navigation("ReceivingAccount");

                    b.Navigation("SendingAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
