// <auto-generated />
using System;
using BankDataWebService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankDataWebService.Migrations
{
    [DbContext(typeof(DBManager))]
    partial class DBManagerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.Property<int>("AccountNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountNo");

                    b.HasIndex("UserName");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNo = 1,
                            AccountType = "savings",
                            Balance = 0m,
                            Pin = 3423,
                            UserName = "sophia3423"
                        },
                        new
                        {
                            AccountNo = 2,
                            AccountType = "cheque",
                            Balance = 0m,
                            Pin = 4353,
                            UserName = "john4534"
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLegal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetAccountNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountNo");

                    b.HasIndex("TargetAccountNo");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            AccountNo = 1,
                            Amount = 134m,
                            IsLegal = true,
                            TimeStamp = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            TransactionId = 2,
                            AccountNo = 2,
                            Amount = 293m,
                            IsLegal = true,
                            TimeStamp = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhoneNo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .HasColumnType("TEXT");

                    b.HasKey("UserName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Password")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "sophia3423",
                            Email = "sophia3423@gmail.com",
                            FirstName = "Sophia",
                            LastName = "Matassa",
                            Password = "9348230249",
                            PhoneNo = 423434332
                        },
                        new
                        {
                            UserName = "john4534",
                            Email = "john4534@gmail.com",
                            FirstName = "John",
                            LastName = "Small",
                            Password = "342345435",
                            PhoneNo = 458392394
                        });
                });

            modelBuilder.Entity("BankDataWebService.Models.Account", b =>
                {
                    b.HasOne("BankDataWebService.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankDataWebService.Models.Transaction", b =>
                {
                    b.HasOne("BankDataWebService.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountNo")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BankDataWebService.Models.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountNo");

                    b.Navigation("Account");

                    b.Navigation("TargetAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
